import { StyleSheet } from 'react-native';
import Colors from '../../assets/colors';
import { material } from 'react-native-typography';
import { floor } from 'react-native-reanimated';

export default StyleSheet.create({
  multiSelectContainer: {
    display: 'flex',
    width: '70%',
    overflow: 'scroll',
    alignItems: 'center',
    justifyContent: 'flex-start',
    backgroundColor: 'transparent',
  },
  fieldSetOverRide: {
    width: '100%',
    marginBottom: 0,
  },
  inputSelectView: {
    flex: 0.75,
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    backgroundColor: Colors.white,
  },
  inputText: {
    ...material.titleObject,
    opacity: 0.4,
    fontSize: 16,
    color: Colors.primary,
  },
  selectContainer: {
    flex: 1,
    height: 50,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
    width: '100%',
    paddingLeft: 0,
    marginBottom: '4%',
    backgroundColor: 'transparent',
  },
  listContainer: {
    flex: 1,
    maxHeight: 200,
    width: '100%',
    overflow: 'scroll',
    padding: 10,
    paddingTop: 0,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'center',
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 4,
    backgroundColor: Colors.white,
  },
  item: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.white,
    height: 30,
    paddingHorizontal: 10,
  },
  selectedItem: {
    backgroundColor: Colors.secondary,
  },
  title: {
    ...material.captionObject,
    fontSize: 14,
    textAlignVertical: 'center',
  },
  selectedTitle: {
    color: Colors.white,
  },
  searchSection: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingLeft: 10,
    borderBottomRightRadius: 4,
    backgroundColor: Colors.white,
  },
  searchIcon: {
    flex: 0.1,
    width: '100%',
    height: '100%',
    textAlignVertical: 'center',
    paddingRight: 20,
    backgroundColor: Colors.white,
  },
  searchInput: {
    flex: 0.9,
    ...material.titleObject,
    color: Colors.primary,
    opacity: 0.8,
    fontSize: 16,
    paddingLeft: 10,
    borderBottomLeftRadius: 4,
    backgroundColor: Colors.white,
  },
  profContainer: {
    flex: 0.2,
    width: '100%',
    paddingVertical: 5,
    display: 'flex',
    position: 'absolute',
    top: 60,
    flexWrap: 'wrap',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  profTag: {
    height: 30,
    borderRadius: 6,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    margin: 4,
    justifyContent: 'center',
    backgroundColor: Colors.secondary,
  },
  profText: {
    ...material.body1Object,
    color: Colors.white,
  },
  overflowNone: {
    overflow: 'hidden',
    elevation: 0.5,
    borderRadius: 6,
    margin: 4,
    shadowColor: Colors.primary,
  },
});
